---
name: ✨ 功能请求
description: 建议新功能或改进现有功能
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ 功能请求

        感谢您提出功能建议！请详细描述您想要的功能。

  - type: textarea
    id: summary
    attributes:
      label: 功能概述
      description: 请简要描述您想要的功能
      placeholder: 我希望能够...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解决的问题
      description: 这个功能解决了什么问题或满足什么需求？
      placeholder: 当前的解决方案有以下问题...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 您希望如何实现这个功能？
      placeholder: 我建议添加一个新的页面/API/组件...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您考虑过哪些替代方案？
      placeholder: 我也考虑过...但这些方案有以下缺点...

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 这个功能的优先级如何？
      options:
        - 低 - 锦上添花的功能
        - 中 - 有用的改进
        - 高 - 重要的功能增强
        - 紧急 - 关键功能缺失
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 实现复杂度
      description: 您认为这个功能的实现复杂度如何？
      options:
        - 低 - 小改动，几天内完成
        - 中 - 需要一定开发工作
        - 高 - 需要大量开发和测试
        - 很高 - 涉及架构变更或新技术
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: 使用场景
      description: 请描述这个功能的具体使用场景
      placeholder: |
        1. 用户在...时
        2. 需要进行...
        3. 期望结果是...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: 界面设计草图
      description: 如果是界面相关功能，请描述或提供设计草图
      placeholder: 描述界面的布局、交互方式等

  - type: textarea
    id: dependencies
    attributes:
      label: 相关依赖
      description: 这个功能是否依赖其他功能或外部服务？
      placeholder: 依赖于用户认证系统、外部 API 等

  - type: textarea
    id: additional
    attributes:
      label: 附加信息
      description: 其他相关信息或参考资料
      placeholder: 类似产品的实现、相关链接等

  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 请确认以下信息
      options:
        - label: 这个功能不与现有功能重复
          required: true
        - label: 我已经搜索了现有的 issues 和功能请求
          required: true
        - label: 这个功能符合项目的整体目标和方向
          required: false